version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/rails
    environment:
      - DATABASE_NAME=db_example
      - DATABASE_USERNAME=admin
      - DATABASE_PASS=123123
      - DATABASE_HOST=172.18.0.1
      - DATABASE_PORT=5432
    # ports:
    #   - 3000:3000
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      # - 8080:80
  red:
    image: node_red
